# ValkeyCluster configuration - these values are directly merged into the parent's `cluster:` alias
enabled: true
name: "valkey-cluster"
shards: 3
replicas: 1
image:
  repository: valkey/valkey
  tag: 9.0.4-trixie
  pullPolicy: IfNotPresent
exporter:
  enabled: false
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
nodeSelector: {}
tolerations: []
affinity: {}

startupProbe:
  tcpSocket:
    port: 6379
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 30

dataStorage:
  enabled: true
  persistentVolumeClaimName: ""
  subPath: ""
  volumeName: "valkey-data"
  requestedSize: "5Gi"
  className: vsphere-db
  accessModes:
    - ReadWriteOnce
  keepPvc: true
  annotations: {}
  labels: {}