{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "valkey-operator.fullname" . }}-network
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "valkey-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
{{ toYaml .Values.networkPolicy.podSelector.matchLabels | indent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          {{ .Values.networkPolicy.allowedNamespaceLabelKey }}: {{ .Values.networkPolicy.allowedNamespaceLabelValue | quote }}
    ports:
    - protocol: TCP
      port: {{ .Values.networkPolicy.port }}
{{- end }}
