apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "valkey-operator.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "valkey-operator.labels" . | nindent 4 }}