{{- if .Values.valkeyCluster.create }}
apiVersion: valkey.io/v1alpha1
kind: ValkeyCluster
metadata:
  name: {{ .Values.valkeyCluster.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey-operator.labels" . | nindent 4 }}
spec:
  shards: {{ .Values.valkeyCluster.shards }}
  replicas: {{ .Values.valkeyCluster.replicas }}
  {{- with .Values.valkeyCluster.image }}
  image: {{ . }}
  {{- end }}
  {{- with .Values.valkeyCluster.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.valkeyCluster.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.valkeyCluster.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.valkeyCluster.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
